### ISSUE TITLE
Suggested padding is too small for me

### ISSUE THREAD

**Issue by t1m0thyj** [EktoHunter/ApertureTerminal#2]
Using Windows Terminal 1.7.1033.0 and the suggested padding is too small for me:
`"padding": "40, 24, 24, 24"`
![image](https://user-images.githubusercontent.com/22344007/120332928-33499580-c2bd-11eb-9f87-6be0e029c121.png)

I've increased the padding to the following:
`"padding": "64, 44, 44, 44"`
![image](https://user-images.githubusercontent.com/22344007/120333222-79065e00-c2bd-11eb-9b45-d0a98b15b1a5.png)

I'm not sure why I need different padding values to get the same appearance, but thought I'd share in case anyone else has the same experience.

**Comment by EktoHunter** [comment]
This is going to happen if your screen either has a different resolution or if you're using full-screen since the values are in pixels and not proportionate to the window. I'll add a comment in README.md to change these values if they don't fit.
